baseURL = "//ecstaticmorse.net/"
languageCode = "en-us"
title = "ecstaticmorse"
theme = "fuji"
enableRobotsTXT = true

[params]
author = "Dylan MacKenzie"
license = "CC BY 4.0"
licenseLink = "https://creativecommons.org/licenses/by/4.0/legalcode"
showLicenseInFooter = true

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
