baseURL = "//ecstaticmorse.net/"
languageCode = "en-us"
title = "ecstaticmorse"
theme = "fuji"
enableRobotsTXT = true

[params]
author = "Dylan MacKenzie"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
